{{- range $agentpools := .Values.agentpools }}
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedMachinePool
metadata:
  name: {{ $agentpools.name }}
spec:
  osDiskSizeGB: {{ $agentpools.osDiskSizeGB }}
  sku: {{ $agentpools.sku }}
---
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: {{ $agentpools.name }}
spec:
  clusterName: {{ $.Values.cluster.name }}
  replicas: {{ $agentpools.nodecount }}
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ $.Values.cluster.name }}
      infrastructureRef:
        apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AzureManagedMachinePool
        name: {{ $agentpools.name }}
      version: {{ $.Values.controlplane.kubernetes_version }}
---
{{- end }}