apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedControlPlane
metadata:
  name: {{ .Values.cluster.name }}
spec:
  defaultPoolRef:
    name: {{ (index .Values.agentpools 0).name }}
  location: {{ .Values.cluster.location }}
  resourceGroupName: {{ .Values.cluster.resourceGroupName }}
  nodeResourceGroupName: {{ .Values.cluster.nodeResourceGroupName }}
  sshPublicKey: {{ .Values.controlplane.sshPublicKey | b64enc }}
  subscriptionID: {{ .Values.subscriptionID }}
  version: {{ .Values.controlplane.kubernetes_version }}
  networkPolicy: {{ .Values.controlplane.networkPolicy }} 
  networkPlugin: {{ .Values.controlplane.networkPlugin }} 