apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  labels:
    {{- include "azure-managed-cluster.labels" . | nindent 4 }}
  name: {{ .Values.cluster.name }}
spec:
  clusterNetwork:
    services:
      cidrBlocks:
        {{- toYaml .Values.cluster.cidrBlocks | nindent 6 }}
  controlPlaneRef:
    apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureManagedControlPlane
    name: {{ .Values.cluster.name }}
  infrastructureRef:
    apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureManagedCluster
    name: {{ .Values.cluster.name }}