apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters
spec:
  generators:
  - list:
      elements:
      - cluster: aks3
        pool0size: Standard_B4ms
        pool1size: Standard_B4ms
      - cluster: aks4
        pool0size: Standard_B4ms
        pool1size: Standard_B4ms
  template:
    metadata:
      name: '{{cluster}}'
    spec:
        destination:
          namespace: clusters
          server: https://kubernetes.default.svc
        project: default
      source:
        helm:
          values: |
              subscriptionID: 12c7e9d6-967e-40c8-8b3e-4659a4ada3ef
              cluster:
                resourceGroupName: aksclusters
                nodeResourceGroupName: '{{cluster}}'-rg
                name: '{{cluster}}'
                controlplane:
                  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIOxg+goSYoCIND3IIAjPoPGr7gsux9OQjE5IP2wEU8eMsywgGXBwZXUVjh8NgFHVWZEMTQCAM52P2ipYBup9QhuqWVjH4v0hrj1X/rx7tzlZh2wk3kgVPQwMKCyacQLifqus4quJLSQAPu1ksgxaWEBWnSa0e+DM2D0PYs/j284qOO9T9ULqpb/ZJK9gySa+AfSMhGCskcT/EfE8g1iqC96PajFxGHOBxqiDFtIKPhNiqKYruDhVJYmhAXG6ScHadiXzP3BdiPR66eyCOQtSeIxjnEeJcrZ7vZLFpWQvaaZw+JfPkGGFCsBTn39dfr1awrMtPIPvkj4iU1jkGKzUD alessandro@A
                agentpools:
                  - name: '{{cluster}}'pool0
                    nodecount: 1
                    sku: '{{pool0size}}'
                    osDiskSizeGB: 100
                  - name: '{{cluster}}'pool1
                    nodecount: 1
                    sku: Standard_B4ms
                    osDiskSizeGB: 100 
        repoURL: https://github.com/ams0/multicluster-capz-argo.git
        targetRevision: HEAD
        path: charts/azure-managed-cluster